[/]
advanced-paste-replace-tabs=true
auto-hide-mouse=true
close-with-last-session=true
control-click-titlebar=true
control-scroll-zoom=true
enable-wide-handle=true
middle-click-close=true
paste-strip-first-char=false
prompt-on-close=true
prompt-on-delete-profile=true
sidebar-on-right=false
tab-position='right'
terminal-title-show-when-single=false
terminal-title-style='none'
use-tabs=false
warn-vte-config-issue=false
window-save-state=false
window-style='normal'

[keybindings]
session-switch-to-terminal-0='<Primary>parenright'
session-switch-to-terminal-1='<Primary>1'
session-switch-to-terminal-2='<Primary>2'
session-switch-to-terminal-3='<Primary>3'
session-switch-to-terminal-4='<Primary>4'
session-switch-to-terminal-5='<Primary>5'
session-switch-to-terminal-6='<Primary>6'
session-switch-to-terminal-7='<Primary>7'
session-switch-to-terminal-8='<Primary>8'
session-switch-to-terminal-9='<Primary>9'
terminal-advanced-paste='<Primary><Alt>v'
terminal-file-browser='<Primary><Alt>o'
terminal-find='<Primary>f'
terminal-layout='disabled'
terminal-maximize='<Primary><Alt>z'

[profiles]
list=['2b7c4080-0ddd-46c5-8f23-563fd3ba789d']

[profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
automatic-switch=@as []
background-color='#282C34'
background-transparency-percent=3
badge-color-set=false
bold-color-set=false
cursor-background-color='#A1B0B8'
cursor-colors-set=false
cursor-foreground-color='#BDC3C7'
cursor-shape='ibeam'
font='SauceCodePro Nerd Font 12'
foreground-color='#ABB2BF'
highlight-colors-set=false
login-shell=true
palette=['#000000', '#E06C75', '#98C379', '#D19A66', '#61AEEE', '#C678DD', '#56B6C2', '#ABB2BF', '#5C6370', '#E06C75', '#98C379', '#D19A66', '#62AFEE', '#C678DD', '#56B6C2', '#FFFFFF']
use-system-font=false
use-theme-colors=false
visible-name='Default'
