format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_status\
$rust\
$nodejs\
$lua\
$golang\
$python\
$c\
$terraform\
$line_break\
$jobs\
$character"""

right_format = "$cmd_duration"

[character]
success_symbol = "[»](purple)"
error_symbol = "[»](red)"

[directory]
read_only = " "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "

[jobs]
symbol = ""

[c]
symbol = " "

[golang]
symbol = " "

[lua]
format = "via [ $version](bold blue) "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[docker_context]
symbol = " "
disabled = true

[memory_usage]
symbol = " "
disabled = true

[package]
disabled = true

[kubernetes]
symbol = "☸ "
style = "blue"
format = "[$symbol$context( \\($namespace\\))]($style) in "
disabled = false
