set $default_sink alsa_output.pci-0000_00_1b.0.analog-stereo

bindsym XF86AudioRaiseVolume        exec pactl set-sink-volume $default_sink +5%

bindsym XF86AudioLowerVolume        exec pactl set-sink-volume $default_sink -5%

bindsym $mod+XF86AudioLowerVolume   exec pactl set-sink-mute $default_sink toggle

# Screen brightness
bindsym XF86MonBrightnessUp exec brightnessctl set '+5%'
bindsym XF86MonBrightnessDown exec brightnessctl set '5%-'

