input type:keyboard {
    xkb_layout us,gr
    xkb_variant ,extended
    xkb_options grp:win_space_toggle,caps:swapescape
}

input type:touchpad {
    # left_handed enabled
    # tap enabled
    natural_scroll enabled
    # dwt enabled
    pointer_accel 0.1 # set mouse sensitivity (between -1 and 1)
    drag enabled
}

input "1133:49970:Logitech_Gaming_Mouse_G502" {
    pointer_accel 1
    accel_profile flat
}
