abbr --add btm "btm --color nord -c"
abbr --add rsync "rsync --progress"
abbr --add cp "cp -i -v"
abbr --add rm "rm -i -v"
abbr --add dd "dd status=progress"
abbr --add sshfs sshfs -o idmap=user,ServerAliveInterval=5,ServerAliveCountMax=3,reconnect

# Git related
abbr --add g "git"
abbr --add ga "git add"
abbr --add glo "git log --oneline"
abbr --add gs "git status"
abbr --add gst "git stash"
abbr --add gco "git checkout (git branch | tr -d ' ' | fzf)"
abbr --add gc "git commit -v"
abbr --add gcm "git commit -m"
abbr --add gca "git commit -v --amend"
abbr --add gcan "git commit --amend --no-edit"
abbr --add ga "git add"
abbr --add gd "git diff"
