#!/usr/bin/env bash

YELLOW='\033[0;33m'
NC='\033[0m'

dest=$HOME/Projects/tmp/neovim
current_dir=$(pwd)

build() {
    echo -e "${YELLOW} make && make install ${NC}"
    make CMAKE_BUILD_TYPE=Release -j16

    echo -e "${YELLOW} Clean up previous installation files ${NC}"
    sudo rm -rf /usr/local/share/nvim/runtime
    sudo rm -rf /usr/local/bin/nvim
    sudo rm -rf /usr/local/lib/nvim

    sudo make install

}

if [ -d "$dest" ]; then
    cd "$dest" || return
    echo -e "${YELLOW} Clean up build files ${NC}"
    make clean
    make distclean

    git pull
    build
    cd "$current_dir" || return
else
    git clone https://github.com/neovim/neovim "$dest"
    cd "$dest" || return
    build
    cd "$current_dir" || return
fi
