#!/usr/bin/env bash

# Download the latest nightly release of rust analyzer and move it to $PATH

wget https://github.com/rust-lang/rust-analyzer/releases/download/nightly/rust-analyzer-x86_64-unknown-linux-gnu.gz -O /tmp/rust-analyzer.gz
gzip -d /tmp/rust-analyzer.gz

RA_PATH="$HOME/.local/bin"

if [ -f "$RA_PATH/rust-analyzer" ]; then
    mv "$HOME/.local/bin/rust-analyzer" "$HOME/.local/bin/rust-analyzer.old"
fi

mv /tmp/rust-analyzer "$RA_PATH"
chmod +x "$RA_PATH/rust-analyzer"
