#!/bin/bash

ext="${1##*.}"
mpvFiles="mkv mp4 gif webm gifv"
fehFiles="png jpg jpeg jpe"
wgetFiles="mp3 flac opus mp3?source=feed pdf"

if echo $fehFiles | grep -w $ext > /dev/null; then
	setsid nohup feh -Z "$1" >/dev/null & disown
elif echo $mpvFiles | grep -w $ext > /dev/null; then
	setsid nohup mpv -quiet "$1" > /dev/null & disown
elif echo $wgetFiles | grep -w $ext > /dev/null; then
	wget "$1" >/dev/null & disown
else
	setsid nohup $BROWSER "$1" 2>/dev/null & disown
fi
