#!/usr/bin/env bash

QUERY="$1"
VGREP_PREFIX="vgrep --no-header "
FZF_DEFAULT_COMMAND="$VGREP_PREFIX '$QUERY'" \
    fzf --bind "change:reload:$VGREP_PREFIX {q} || true" --ansi --phony --tac --query "$INITIAL_QUERY" \
    | awk '{print $1}' | xargs -I{} -o vgrep --show {}

