#!/bin/bash

# Small script to enable root access to x-windows system

xhost +SI:localuser:root
sudo $1

# disable root access after application terminates
xhost -SI:localuser:root

# Print access status to allow verification that root access was removed
xhost
